// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: vacancy/v1/vacancy.proto

package vacancyv1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type VacancySearchField int32

const (
	VacancySearchField_VACANCY_SEARCH_FIELD_UNSPECIFIED  VacancySearchField = 0
	VacancySearchField_VACANCY_SEARCH_FIELD_TITLE        VacancySearchField = 1
	VacancySearchField_VACANCY_SEARCH_FIELD_DESCRIPTION  VacancySearchField = 2
	VacancySearchField_VACANCY_SEARCH_FIELD_COMPANY_NAME VacancySearchField = 3
)

// Enum value maps for VacancySearchField.
var (
	VacancySearchField_name = map[int32]string{
		0: "VACANCY_SEARCH_FIELD_UNSPECIFIED",
		1: "VACANCY_SEARCH_FIELD_TITLE",
		2: "VACANCY_SEARCH_FIELD_DESCRIPTION",
		3: "VACANCY_SEARCH_FIELD_COMPANY_NAME",
	}
	VacancySearchField_value = map[string]int32{
		"VACANCY_SEARCH_FIELD_UNSPECIFIED":  0,
		"VACANCY_SEARCH_FIELD_TITLE":        1,
		"VACANCY_SEARCH_FIELD_DESCRIPTION":  2,
		"VACANCY_SEARCH_FIELD_COMPANY_NAME": 3,
	}
)

func (x VacancySearchField) Enum() *VacancySearchField {
	p := new(VacancySearchField)
	*p = x
	return p
}

func (x VacancySearchField) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (VacancySearchField) Descriptor() protoreflect.EnumDescriptor {
	return file_vacancy_v1_vacancy_proto_enumTypes[0].Descriptor()
}

func (VacancySearchField) Type() protoreflect.EnumType {
	return &file_vacancy_v1_vacancy_proto_enumTypes[0]
}

func (x VacancySearchField) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use VacancySearchField.Descriptor instead.
func (VacancySearchField) EnumDescriptor() ([]byte, []int) {
	return file_vacancy_v1_vacancy_proto_rawDescGZIP(), []int{0}
}

type VacancySort int32

const (
	VacancySort_VACANCY_SORT_UNSPECIFIED VacancySort = 0
	VacancySort_VACANCY_SORT_DATE_DESC   VacancySort = 1
	VacancySort_VACANCY_SORT_DATE_ASC    VacancySort = 2
	VacancySort_VACANCY_SORT_SALARY_DESC VacancySort = 3
	VacancySort_VACANCY_SORT_SALARY_ASC  VacancySort = 4
)

// Enum value maps for VacancySort.
var (
	VacancySort_name = map[int32]string{
		0: "VACANCY_SORT_UNSPECIFIED",
		1: "VACANCY_SORT_DATE_DESC",
		2: "VACANCY_SORT_DATE_ASC",
		3: "VACANCY_SORT_SALARY_DESC",
		4: "VACANCY_SORT_SALARY_ASC",
	}
	VacancySort_value = map[string]int32{
		"VACANCY_SORT_UNSPECIFIED": 0,
		"VACANCY_SORT_DATE_DESC":   1,
		"VACANCY_SORT_DATE_ASC":    2,
		"VACANCY_SORT_SALARY_DESC": 3,
		"VACANCY_SORT_SALARY_ASC":  4,
	}
)

func (x VacancySort) Enum() *VacancySort {
	p := new(VacancySort)
	*p = x
	return p
}

func (x VacancySort) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (VacancySort) Descriptor() protoreflect.EnumDescriptor {
	return file_vacancy_v1_vacancy_proto_enumTypes[1].Descriptor()
}

func (VacancySort) Type() protoreflect.EnumType {
	return &file_vacancy_v1_vacancy_proto_enumTypes[1]
}

func (x VacancySort) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use VacancySort.Descriptor instead.
func (VacancySort) EnumDescriptor() ([]byte, []int) {
	return file_vacancy_v1_vacancy_proto_rawDescGZIP(), []int{1}
}

type VacancyPeriod int32

const (
	VacancyPeriod_VACANCY_PERIOD_UNSPECIFIED VacancyPeriod = 0
	VacancyPeriod_VACANCY_PERIOD_DAY         VacancyPeriod = 1
	VacancyPeriod_VACANCY_PERIOD_THREE_DAYS  VacancyPeriod = 2
	VacancyPeriod_VACANCY_PERIOD_WEEK        VacancyPeriod = 3
)

// Enum value maps for VacancyPeriod.
var (
	VacancyPeriod_name = map[int32]string{
		0: "VACANCY_PERIOD_UNSPECIFIED",
		1: "VACANCY_PERIOD_DAY",
		2: "VACANCY_PERIOD_THREE_DAYS",
		3: "VACANCY_PERIOD_WEEK",
	}
	VacancyPeriod_value = map[string]int32{
		"VACANCY_PERIOD_UNSPECIFIED": 0,
		"VACANCY_PERIOD_DAY":         1,
		"VACANCY_PERIOD_THREE_DAYS":  2,
		"VACANCY_PERIOD_WEEK":        3,
	}
)

func (x VacancyPeriod) Enum() *VacancyPeriod {
	p := new(VacancyPeriod)
	*p = x
	return p
}

func (x VacancyPeriod) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (VacancyPeriod) Descriptor() protoreflect.EnumDescriptor {
	return file_vacancy_v1_vacancy_proto_enumTypes[2].Descriptor()
}

func (VacancyPeriod) Type() protoreflect.EnumType {
	return &file_vacancy_v1_vacancy_proto_enumTypes[2]
}

func (x VacancyPeriod) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use VacancyPeriod.Descriptor instead.
func (VacancyPeriod) EnumDescriptor() ([]byte, []int) {
	return file_vacancy_v1_vacancy_proto_rawDescGZIP(), []int{2}
}

type GetVacancyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVacancyRequest) Reset() {
	*x = GetVacancyRequest{}
	mi := &file_vacancy_v1_vacancy_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVacancyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVacancyRequest) ProtoMessage() {}

func (x *GetVacancyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vacancy_v1_vacancy_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVacancyRequest.ProtoReflect.Descriptor instead.
func (*GetVacancyRequest) Descriptor() ([]byte, []int) {
	return file_vacancy_v1_vacancy_proto_rawDescGZIP(), []int{0}
}

func (x *GetVacancyRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetVacancyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Vacancy       *Vacancy               `protobuf:"bytes,1,opt,name=vacancy,proto3" json:"vacancy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVacancyResponse) Reset() {
	*x = GetVacancyResponse{}
	mi := &file_vacancy_v1_vacancy_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVacancyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVacancyResponse) ProtoMessage() {}

func (x *GetVacancyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vacancy_v1_vacancy_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVacancyResponse.ProtoReflect.Descriptor instead.
func (*GetVacancyResponse) Descriptor() ([]byte, []int) {
	return file_vacancy_v1_vacancy_proto_rawDescGZIP(), []int{1}
}

func (x *GetVacancyResponse) GetVacancy() *Vacancy {
	if x != nil {
		return x.Vacancy
	}
	return nil
}

// ListVacanciesRequest contains both pagination and optional filters. An empty
// filter returns all vacancies, so clients do not need a second list RPC.
type ListVacanciesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          *int32                 `protobuf:"varint,1,opt,name=page,proto3,oneof" json:"page,omitempty"`
	ItemsPerPage  *int32                 `protobuf:"varint,2,opt,name=items_per_page,json=itemsPerPage,proto3,oneof" json:"items_per_page,omitempty"`
	Keyword       *string                `protobuf:"bytes,3,opt,name=keyword,proto3,oneof" json:"keyword,omitempty"`
	Cities        []string               `protobuf:"bytes,4,rep,name=cities,proto3" json:"cities,omitempty"`
	SearchFields  []VacancySearchField   `protobuf:"varint,5,rep,packed,name=search_fields,json=searchFields,proto3,enum=jobaggregator.vacancy.v1.VacancySearchField" json:"search_fields,omitempty"`
	MinSalary     *float64               `protobuf:"fixed64,6,opt,name=min_salary,json=minSalary,proto3,oneof" json:"min_salary,omitempty"`
	MaxSalary     *float64               `protobuf:"fixed64,7,opt,name=max_salary,json=maxSalary,proto3,oneof" json:"max_salary,omitempty"`
	Sort          VacancySort            `protobuf:"varint,8,opt,name=sort,proto3,enum=jobaggregator.vacancy.v1.VacancySort" json:"sort,omitempty"`
	Period        VacancyPeriod          `protobuf:"varint,9,opt,name=period,proto3,enum=jobaggregator.vacancy.v1.VacancyPeriod" json:"period,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListVacanciesRequest) Reset() {
	*x = ListVacanciesRequest{}
	mi := &file_vacancy_v1_vacancy_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListVacanciesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListVacanciesRequest) ProtoMessage() {}

func (x *ListVacanciesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vacancy_v1_vacancy_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListVacanciesRequest.ProtoReflect.Descriptor instead.
func (*ListVacanciesRequest) Descriptor() ([]byte, []int) {
	return file_vacancy_v1_vacancy_proto_rawDescGZIP(), []int{2}
}

func (x *ListVacanciesRequest) GetPage() int32 {
	if x != nil && x.Page != nil {
		return *x.Page
	}
	return 0
}

func (x *ListVacanciesRequest) GetItemsPerPage() int32 {
	if x != nil && x.ItemsPerPage != nil {
		return *x.ItemsPerPage
	}
	return 0
}

func (x *ListVacanciesRequest) GetKeyword() string {
	if x != nil && x.Keyword != nil {
		return *x.Keyword
	}
	return ""
}

func (x *ListVacanciesRequest) GetCities() []string {
	if x != nil {
		return x.Cities
	}
	return nil
}

func (x *ListVacanciesRequest) GetSearchFields() []VacancySearchField {
	if x != nil {
		return x.SearchFields
	}
	return nil
}

func (x *ListVacanciesRequest) GetMinSalary() float64 {
	if x != nil && x.MinSalary != nil {
		return *x.MinSalary
	}
	return 0
}

func (x *ListVacanciesRequest) GetMaxSalary() float64 {
	if x != nil && x.MaxSalary != nil {
		return *x.MaxSalary
	}
	return 0
}

func (x *ListVacanciesRequest) GetSort() VacancySort {
	if x != nil {
		return x.Sort
	}
	return VacancySort_VACANCY_SORT_UNSPECIFIED
}

func (x *ListVacanciesRequest) GetPeriod() VacancyPeriod {
	if x != nil {
		return x.Period
	}
	return VacancyPeriod_VACANCY_PERIOD_UNSPECIFIED
}

type ListVacanciesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Vacancies     []*Vacancy             `protobuf:"bytes,1,rep,name=vacancies,proto3" json:"vacancies,omitempty"`
	PageInfo      *PageInfo              `protobuf:"bytes,2,opt,name=page_info,json=pageInfo,proto3" json:"page_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListVacanciesResponse) Reset() {
	*x = ListVacanciesResponse{}
	mi := &file_vacancy_v1_vacancy_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListVacanciesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListVacanciesResponse) ProtoMessage() {}

func (x *ListVacanciesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vacancy_v1_vacancy_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListVacanciesResponse.ProtoReflect.Descriptor instead.
func (*ListVacanciesResponse) Descriptor() ([]byte, []int) {
	return file_vacancy_v1_vacancy_proto_rawDescGZIP(), []int{3}
}

func (x *ListVacanciesResponse) GetVacancies() []*Vacancy {
	if x != nil {
		return x.Vacancies
	}
	return nil
}

func (x *ListVacanciesResponse) GetPageInfo() *PageInfo {
	if x != nil {
		return x.PageInfo
	}
	return nil
}

type CreateVacancyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Salary        float64                `protobuf:"fixed64,3,opt,name=salary,proto3" json:"salary,omitempty"`
	Link          string                 `protobuf:"bytes,4,opt,name=link,proto3" json:"link,omitempty"`
	City          string                 `protobuf:"bytes,5,opt,name=city,proto3" json:"city,omitempty"`
	CompanyName   string                 `protobuf:"bytes,6,opt,name=company_name,json=companyName,proto3" json:"company_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateVacancyRequest) Reset() {
	*x = CreateVacancyRequest{}
	mi := &file_vacancy_v1_vacancy_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateVacancyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateVacancyRequest) ProtoMessage() {}

func (x *CreateVacancyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vacancy_v1_vacancy_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateVacancyRequest.ProtoReflect.Descriptor instead.
func (*CreateVacancyRequest) Descriptor() ([]byte, []int) {
	return file_vacancy_v1_vacancy_proto_rawDescGZIP(), []int{4}
}

func (x *CreateVacancyRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateVacancyRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateVacancyRequest) GetSalary() float64 {
	if x != nil {
		return x.Salary
	}
	return 0
}

func (x *CreateVacancyRequest) GetLink() string {
	if x != nil {
		return x.Link
	}
	return ""
}

func (x *CreateVacancyRequest) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *CreateVacancyRequest) GetCompanyName() string {
	if x != nil {
		return x.CompanyName
	}
	return ""
}

type CreateVacancyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Vacancy       *Vacancy               `protobuf:"bytes,1,opt,name=vacancy,proto3" json:"vacancy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateVacancyResponse) Reset() {
	*x = CreateVacancyResponse{}
	mi := &file_vacancy_v1_vacancy_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateVacancyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateVacancyResponse) ProtoMessage() {}

func (x *CreateVacancyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vacancy_v1_vacancy_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateVacancyResponse.ProtoReflect.Descriptor instead.
func (*CreateVacancyResponse) Descriptor() ([]byte, []int) {
	return file_vacancy_v1_vacancy_proto_rawDescGZIP(), []int{5}
}

func (x *CreateVacancyResponse) GetVacancy() *Vacancy {
	if x != nil {
		return x.Vacancy
	}
	return nil
}

type BatchCreateVacanciesRequest struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Vacancies     []*CreateVacancyRequest `protobuf:"bytes,1,rep,name=vacancies,proto3" json:"vacancies,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchCreateVacanciesRequest) Reset() {
	*x = BatchCreateVacanciesRequest{}
	mi := &file_vacancy_v1_vacancy_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchCreateVacanciesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchCreateVacanciesRequest) ProtoMessage() {}

func (x *BatchCreateVacanciesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vacancy_v1_vacancy_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchCreateVacanciesRequest.ProtoReflect.Descriptor instead.
func (*BatchCreateVacanciesRequest) Descriptor() ([]byte, []int) {
	return file_vacancy_v1_vacancy_proto_rawDescGZIP(), []int{6}
}

func (x *BatchCreateVacanciesRequest) GetVacancies() []*CreateVacancyRequest {
	if x != nil {
		return x.Vacancies
	}
	return nil
}

type BatchCreateVacanciesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Vacancies     []*Vacancy             `protobuf:"bytes,1,rep,name=vacancies,proto3" json:"vacancies,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchCreateVacanciesResponse) Reset() {
	*x = BatchCreateVacanciesResponse{}
	mi := &file_vacancy_v1_vacancy_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchCreateVacanciesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchCreateVacanciesResponse) ProtoMessage() {}

func (x *BatchCreateVacanciesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vacancy_v1_vacancy_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchCreateVacanciesResponse.ProtoReflect.Descriptor instead.
func (*BatchCreateVacanciesResponse) Descriptor() ([]byte, []int) {
	return file_vacancy_v1_vacancy_proto_rawDescGZIP(), []int{7}
}

func (x *BatchCreateVacanciesResponse) GetVacancies() []*Vacancy {
	if x != nil {
		return x.Vacancies
	}
	return nil
}

type PageInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	ItemsPerPage  int32                  `protobuf:"varint,2,opt,name=items_per_page,json=itemsPerPage,proto3" json:"items_per_page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PageInfo) Reset() {
	*x = PageInfo{}
	mi := &file_vacancy_v1_vacancy_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PageInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PageInfo) ProtoMessage() {}

func (x *PageInfo) ProtoReflect() protoreflect.Message {
	mi := &file_vacancy_v1_vacancy_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PageInfo.ProtoReflect.Descriptor instead.
func (*PageInfo) Descriptor() ([]byte, []int) {
	return file_vacancy_v1_vacancy_proto_rawDescGZIP(), []int{8}
}

func (x *PageInfo) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *PageInfo) GetItemsPerPage() int32 {
	if x != nil {
		return x.ItemsPerPage
	}
	return 0
}

type Company struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Company) Reset() {
	*x = Company{}
	mi := &file_vacancy_v1_vacancy_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Company) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Company) ProtoMessage() {}

func (x *Company) ProtoReflect() protoreflect.Message {
	mi := &file_vacancy_v1_vacancy_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Company.ProtoReflect.Descriptor instead.
func (*Company) Descriptor() ([]byte, []int) {
	return file_vacancy_v1_vacancy_proto_rawDescGZIP(), []int{9}
}

func (x *Company) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Company) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type Vacancy struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	CompanyId     int64                  `protobuf:"varint,4,opt,name=company_id,json=companyId,proto3" json:"company_id,omitempty"`
	Salary        float64                `protobuf:"fixed64,5,opt,name=salary,proto3" json:"salary,omitempty"`
	Link          string                 `protobuf:"bytes,6,opt,name=link,proto3" json:"link,omitempty"`
	City          string                 `protobuf:"bytes,7,opt,name=city,proto3" json:"city,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Company       *Company               `protobuf:"bytes,10,opt,name=company,proto3" json:"company,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Vacancy) Reset() {
	*x = Vacancy{}
	mi := &file_vacancy_v1_vacancy_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Vacancy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Vacancy) ProtoMessage() {}

func (x *Vacancy) ProtoReflect() protoreflect.Message {
	mi := &file_vacancy_v1_vacancy_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Vacancy.ProtoReflect.Descriptor instead.
func (*Vacancy) Descriptor() ([]byte, []int) {
	return file_vacancy_v1_vacancy_proto_rawDescGZIP(), []int{10}
}

func (x *Vacancy) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Vacancy) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Vacancy) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Vacancy) GetCompanyId() int64 {
	if x != nil {
		return x.CompanyId
	}
	return 0
}

func (x *Vacancy) GetSalary() float64 {
	if x != nil {
		return x.Salary
	}
	return 0
}

func (x *Vacancy) GetLink() string {
	if x != nil {
		return x.Link
	}
	return ""
}

func (x *Vacancy) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *Vacancy) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Vacancy) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Vacancy) GetCompany() *Company {
	if x != nil {
		return x.Company
	}
	return nil
}

var File_vacancy_v1_vacancy_proto protoreflect.FileDescriptor

const file_vacancy_v1_vacancy_proto_rawDesc = "" +
	"\n" +
	"\x18vacancy/v1/vacancy.proto\x12\x18jobaggregator.vacancy.v1\x1a\x1bbuf/validate/validate.proto\x1a\x1fgoogle/protobuf/timestamp.proto\",\n" +
	"\x11GetVacancyRequest\x12\x17\n" +
	"\x02id\x18\x01 \x01(\x03B\a\xbaH\x04\"\x02 \x00R\x02id\"Q\n" +
	"\x12GetVacancyResponse\x12;\n" +
	"\avacancy\x18\x01 \x01(\v2!.jobaggregator.vacancy.v1.VacancyR\avacancy\"\xd8\a\n" +
	"\x14ListVacanciesRequest\x12 \n" +
	"\x04page\x18\x01 \x01(\x05B\a\xbaH\x04\x1a\x02(\x01H\x00R\x04page\x88\x01\x01\x124\n" +
	"\x0eitems_per_page\x18\x02 \x01(\x05B\t\xbaH\x06\x1a\x04\x18d(\x01H\x01R\fitemsPerPage\x88\x01\x01\x12'\n" +
	"\akeyword\x18\x03 \x01(\tB\b\xbaH\x05r\x03\x18\xc8\x01H\x02R\akeyword\x88\x01\x01\x120\n" +
	"\x06cities\x18\x04 \x03(\tB\x18\xbaH\x15\x92\x01\x12\x10\x14\"\x0er\f\x10\x01\x18d2\x06.*\\S.*R\x06cities\x12d\n" +
	"\rsearch_fields\x18\x05 \x03(\x0e2,.jobaggregator.vacancy.v1.VacancySearchFieldB\x11\xbaH\x0e\x92\x01\v\x10\x03\"\a\x82\x01\x04\x10\x01 \x00R\fsearchFields\x124\n" +
	"\n" +
	"min_salary\x18\x06 \x01(\x01B\x10\xbaH\r\x12\v@\x01)\x00\x00\x00\x00\x00\x00\x00\x00H\x03R\tminSalary\x88\x01\x01\x124\n" +
	"\n" +
	"max_salary\x18\a \x01(\x01B\x10\xbaH\r\x12\v@\x01)\x00\x00\x00\x00\x00\x00\x00\x00H\x04R\tmaxSalary\x88\x01\x01\x12C\n" +
	"\x04sort\x18\b \x01(\x0e2%.jobaggregator.vacancy.v1.VacancySortB\b\xbaH\x05\x82\x01\x02\x10\x01R\x04sort\x12I\n" +
	"\x06period\x18\t \x01(\x0e2'.jobaggregator.vacancy.v1.VacancyPeriodB\b\xbaH\x05\x82\x01\x02\x10\x01R\x06period:\xe4\x02\xbaH\xe0\x02\x1a\xaf\x01\n" +
	"\x1flist_vacancies.keyword_required\x123keyword is required when search_fields is specified\x1aWsize(this.search_fields) == 0 || (has(this.keyword) && this.keyword.matches('.*\\\\S.*'))\x1a\xab\x01\n" +
	"\x1blist_vacancies.salary_range\x126max_salary must be greater than or equal to min_salary\x1aT!has(this.min_salary) || !has(this.max_salary) || this.max_salary >= this.min_salaryB\a\n" +
	"\x05_pageB\x11\n" +
	"\x0f_items_per_pageB\n" +
	"\n" +
	"\b_keywordB\r\n" +
	"\v_min_salaryB\r\n" +
	"\v_max_salary\"\x99\x01\n" +
	"\x15ListVacanciesResponse\x12?\n" +
	"\tvacancies\x18\x01 \x03(\v2!.jobaggregator.vacancy.v1.VacancyR\tvacancies\x12?\n" +
	"\tpage_info\x18\x02 \x01(\v2\".jobaggregator.vacancy.v1.PageInfoR\bpageInfo\"\x9f\x02\n" +
	"\x14CreateVacancyRequest\x12(\n" +
	"\x05title\x18\x01 \x01(\tB\x12\xbaH\x0fr\r\x10\x01\x18\xc8\x012\x06.*\\S.*R\x05title\x124\n" +
	"\vdescription\x18\x02 \x01(\tB\x12\xbaH\x0fr\r\x10\x01\x18\x90N2\x06.*\\S.*R\vdescription\x12(\n" +
	"\x06salary\x18\x03 \x01(\x01B\x10\xbaH\r\x12\v@\x01)\x00\x00\x00\x00\x00\x00\x00\x00R\x06salary\x12\x1f\n" +
	"\x04link\x18\x04 \x01(\tB\v\xbaH\br\x06\x18\x80\x10\x88\x01\x01R\x04link\x12%\n" +
	"\x04city\x18\x05 \x01(\tB\x11\xbaH\x0er\f\x10\x01\x18d2\x06.*\\S.*R\x04city\x125\n" +
	"\fcompany_name\x18\x06 \x01(\tB\x12\xbaH\x0fr\r\x10\x01\x18\xc8\x012\x06.*\\S.*R\vcompanyName\"T\n" +
	"\x15CreateVacancyResponse\x12;\n" +
	"\avacancy\x18\x01 \x01(\v2!.jobaggregator.vacancy.v1.VacancyR\avacancy\"x\n" +
	"\x1bBatchCreateVacanciesRequest\x12Y\n" +
	"\tvacancies\x18\x01 \x03(\v2..jobaggregator.vacancy.v1.CreateVacancyRequestB\v\xbaH\b\x92\x01\x05\b\x01\x10\xe8\aR\tvacancies\"_\n" +
	"\x1cBatchCreateVacanciesResponse\x12?\n" +
	"\tvacancies\x18\x01 \x03(\v2!.jobaggregator.vacancy.v1.VacancyR\tvacancies\"D\n" +
	"\bPageInfo\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12$\n" +
	"\x0eitems_per_page\x18\x02 \x01(\x05R\fitemsPerPage\"-\n" +
	"\aCompany\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"\xe3\x02\n" +
	"\aVacancy\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1d\n" +
	"\n" +
	"company_id\x18\x04 \x01(\x03R\tcompanyId\x12\x16\n" +
	"\x06salary\x18\x05 \x01(\x01R\x06salary\x12\x12\n" +
	"\x04link\x18\x06 \x01(\tR\x04link\x12\x12\n" +
	"\x04city\x18\a \x01(\tR\x04city\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12;\n" +
	"\acompany\x18\n" +
	" \x01(\v2!.jobaggregator.vacancy.v1.CompanyR\acompany*\xa7\x01\n" +
	"\x12VacancySearchField\x12$\n" +
	" VACANCY_SEARCH_FIELD_UNSPECIFIED\x10\x00\x12\x1e\n" +
	"\x1aVACANCY_SEARCH_FIELD_TITLE\x10\x01\x12$\n" +
	" VACANCY_SEARCH_FIELD_DESCRIPTION\x10\x02\x12%\n" +
	"!VACANCY_SEARCH_FIELD_COMPANY_NAME\x10\x03*\x9d\x01\n" +
	"\vVacancySort\x12\x1c\n" +
	"\x18VACANCY_SORT_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16VACANCY_SORT_DATE_DESC\x10\x01\x12\x19\n" +
	"\x15VACANCY_SORT_DATE_ASC\x10\x02\x12\x1c\n" +
	"\x18VACANCY_SORT_SALARY_DESC\x10\x03\x12\x1b\n" +
	"\x17VACANCY_SORT_SALARY_ASC\x10\x04*\x7f\n" +
	"\rVacancyPeriod\x12\x1e\n" +
	"\x1aVACANCY_PERIOD_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12VACANCY_PERIOD_DAY\x10\x01\x12\x1d\n" +
	"\x19VACANCY_PERIOD_THREE_DAYS\x10\x02\x12\x17\n" +
	"\x13VACANCY_PERIOD_WEEK\x10\x032\xe5\x03\n" +
	"\x0eVacancyService\x12g\n" +
	"\n" +
	"GetVacancy\x12+.jobaggregator.vacancy.v1.GetVacancyRequest\x1a,.jobaggregator.vacancy.v1.GetVacancyResponse\x12p\n" +
	"\rListVacancies\x12..jobaggregator.vacancy.v1.ListVacanciesRequest\x1a/.jobaggregator.vacancy.v1.ListVacanciesResponse\x12p\n" +
	"\rCreateVacancy\x12..jobaggregator.vacancy.v1.CreateVacancyRequest\x1a/.jobaggregator.vacancy.v1.CreateVacancyResponse\x12\x85\x01\n" +
	"\x14BatchCreateVacancies\x125.jobaggregator.vacancy.v1.BatchCreateVacanciesRequest\x1a6.jobaggregator.vacancy.v1.BatchCreateVacanciesResponseB5Z3vacancy_service/internal/proto/vacancy/v1;vacancyv1b\x06proto3"

var (
	file_vacancy_v1_vacancy_proto_rawDescOnce sync.Once
	file_vacancy_v1_vacancy_proto_rawDescData []byte
)

func file_vacancy_v1_vacancy_proto_rawDescGZIP() []byte {
	file_vacancy_v1_vacancy_proto_rawDescOnce.Do(func() {
		file_vacancy_v1_vacancy_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_vacancy_v1_vacancy_proto_rawDesc), len(file_vacancy_v1_vacancy_proto_rawDesc)))
	})
	return file_vacancy_v1_vacancy_proto_rawDescData
}

var file_vacancy_v1_vacancy_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_vacancy_v1_vacancy_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_vacancy_v1_vacancy_proto_goTypes = []any{
	(VacancySearchField)(0),              // 0: jobaggregator.vacancy.v1.VacancySearchField
	(VacancySort)(0),                     // 1: jobaggregator.vacancy.v1.VacancySort
	(VacancyPeriod)(0),                   // 2: jobaggregator.vacancy.v1.VacancyPeriod
	(*GetVacancyRequest)(nil),            // 3: jobaggregator.vacancy.v1.GetVacancyRequest
	(*GetVacancyResponse)(nil),           // 4: jobaggregator.vacancy.v1.GetVacancyResponse
	(*ListVacanciesRequest)(nil),         // 5: jobaggregator.vacancy.v1.ListVacanciesRequest
	(*ListVacanciesResponse)(nil),        // 6: jobaggregator.vacancy.v1.ListVacanciesResponse
	(*CreateVacancyRequest)(nil),         // 7: jobaggregator.vacancy.v1.CreateVacancyRequest
	(*CreateVacancyResponse)(nil),        // 8: jobaggregator.vacancy.v1.CreateVacancyResponse
	(*BatchCreateVacanciesRequest)(nil),  // 9: jobaggregator.vacancy.v1.BatchCreateVacanciesRequest
	(*BatchCreateVacanciesResponse)(nil), // 10: jobaggregator.vacancy.v1.BatchCreateVacanciesResponse
	(*PageInfo)(nil),                     // 11: jobaggregator.vacancy.v1.PageInfo
	(*Company)(nil),                      // 12: jobaggregator.vacancy.v1.Company
	(*Vacancy)(nil),                      // 13: jobaggregator.vacancy.v1.Vacancy
	(*timestamppb.Timestamp)(nil),        // 14: google.protobuf.Timestamp
}
var file_vacancy_v1_vacancy_proto_depIdxs = []int32{
	13, // 0: jobaggregator.vacancy.v1.GetVacancyResponse.vacancy:type_name -> jobaggregator.vacancy.v1.Vacancy
	0,  // 1: jobaggregator.vacancy.v1.ListVacanciesRequest.search_fields:type_name -> jobaggregator.vacancy.v1.VacancySearchField
	1,  // 2: jobaggregator.vacancy.v1.ListVacanciesRequest.sort:type_name -> jobaggregator.vacancy.v1.VacancySort
	2,  // 3: jobaggregator.vacancy.v1.ListVacanciesRequest.period:type_name -> jobaggregator.vacancy.v1.VacancyPeriod
	13, // 4: jobaggregator.vacancy.v1.ListVacanciesResponse.vacancies:type_name -> jobaggregator.vacancy.v1.Vacancy
	11, // 5: jobaggregator.vacancy.v1.ListVacanciesResponse.page_info:type_name -> jobaggregator.vacancy.v1.PageInfo
	13, // 6: jobaggregator.vacancy.v1.CreateVacancyResponse.vacancy:type_name -> jobaggregator.vacancy.v1.Vacancy
	7,  // 7: jobaggregator.vacancy.v1.BatchCreateVacanciesRequest.vacancies:type_name -> jobaggregator.vacancy.v1.CreateVacancyRequest
	13, // 8: jobaggregator.vacancy.v1.BatchCreateVacanciesResponse.vacancies:type_name -> jobaggregator.vacancy.v1.Vacancy
	14, // 9: jobaggregator.vacancy.v1.Vacancy.created_at:type_name -> google.protobuf.Timestamp
	14, // 10: jobaggregator.vacancy.v1.Vacancy.updated_at:type_name -> google.protobuf.Timestamp
	12, // 11: jobaggregator.vacancy.v1.Vacancy.company:type_name -> jobaggregator.vacancy.v1.Company
	3,  // 12: jobaggregator.vacancy.v1.VacancyService.GetVacancy:input_type -> jobaggregator.vacancy.v1.GetVacancyRequest
	5,  // 13: jobaggregator.vacancy.v1.VacancyService.ListVacancies:input_type -> jobaggregator.vacancy.v1.ListVacanciesRequest
	7,  // 14: jobaggregator.vacancy.v1.VacancyService.CreateVacancy:input_type -> jobaggregator.vacancy.v1.CreateVacancyRequest
	9,  // 15: jobaggregator.vacancy.v1.VacancyService.BatchCreateVacancies:input_type -> jobaggregator.vacancy.v1.BatchCreateVacanciesRequest
	4,  // 16: jobaggregator.vacancy.v1.VacancyService.GetVacancy:output_type -> jobaggregator.vacancy.v1.GetVacancyResponse
	6,  // 17: jobaggregator.vacancy.v1.VacancyService.ListVacancies:output_type -> jobaggregator.vacancy.v1.ListVacanciesResponse
	8,  // 18: jobaggregator.vacancy.v1.VacancyService.CreateVacancy:output_type -> jobaggregator.vacancy.v1.CreateVacancyResponse
	10, // 19: jobaggregator.vacancy.v1.VacancyService.BatchCreateVacancies:output_type -> jobaggregator.vacancy.v1.BatchCreateVacanciesResponse
	16, // [16:20] is the sub-list for method output_type
	12, // [12:16] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_vacancy_v1_vacancy_proto_init() }
func file_vacancy_v1_vacancy_proto_init() {
	if File_vacancy_v1_vacancy_proto != nil {
		return
	}
	file_vacancy_v1_vacancy_proto_msgTypes[2].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_vacancy_v1_vacancy_proto_rawDesc), len(file_vacancy_v1_vacancy_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_vacancy_v1_vacancy_proto_goTypes,
		DependencyIndexes: file_vacancy_v1_vacancy_proto_depIdxs,
		EnumInfos:         file_vacancy_v1_vacancy_proto_enumTypes,
		MessageInfos:      file_vacancy_v1_vacancy_proto_msgTypes,
	}.Build()
	File_vacancy_v1_vacancy_proto = out.File
	file_vacancy_v1_vacancy_proto_goTypes = nil
	file_vacancy_v1_vacancy_proto_depIdxs = nil
}
