// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: vacancy/v1/vacancy.proto

package vacancyv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetVacancyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVacancyRequest) Reset() {
	*x = GetVacancyRequest{}
	mi := &file_vacancy_v1_vacancy_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVacancyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVacancyRequest) ProtoMessage() {}

func (x *GetVacancyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vacancy_v1_vacancy_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVacancyRequest.ProtoReflect.Descriptor instead.
func (*GetVacancyRequest) Descriptor() ([]byte, []int) {
	return file_vacancy_v1_vacancy_proto_rawDescGZIP(), []int{0}
}

func (x *GetVacancyRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetVacancyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Vacancy       *Vacancy               `protobuf:"bytes,1,opt,name=vacancy,proto3" json:"vacancy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVacancyResponse) Reset() {
	*x = GetVacancyResponse{}
	mi := &file_vacancy_v1_vacancy_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVacancyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVacancyResponse) ProtoMessage() {}

func (x *GetVacancyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vacancy_v1_vacancy_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVacancyResponse.ProtoReflect.Descriptor instead.
func (*GetVacancyResponse) Descriptor() ([]byte, []int) {
	return file_vacancy_v1_vacancy_proto_rawDescGZIP(), []int{1}
}

func (x *GetVacancyResponse) GetVacancy() *Vacancy {
	if x != nil {
		return x.Vacancy
	}
	return nil
}

type ListVacanciesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          *int32                 `protobuf:"varint,1,opt,name=page,proto3,oneof" json:"page,omitempty"`
	ItemsPerPage  *int32                 `protobuf:"varint,2,opt,name=items_per_page,json=itemsPerPage,proto3,oneof" json:"items_per_page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListVacanciesRequest) Reset() {
	*x = ListVacanciesRequest{}
	mi := &file_vacancy_v1_vacancy_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListVacanciesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListVacanciesRequest) ProtoMessage() {}

func (x *ListVacanciesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vacancy_v1_vacancy_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListVacanciesRequest.ProtoReflect.Descriptor instead.
func (*ListVacanciesRequest) Descriptor() ([]byte, []int) {
	return file_vacancy_v1_vacancy_proto_rawDescGZIP(), []int{2}
}

func (x *ListVacanciesRequest) GetPage() int32 {
	if x != nil && x.Page != nil {
		return *x.Page
	}
	return 0
}

func (x *ListVacanciesRequest) GetItemsPerPage() int32 {
	if x != nil && x.ItemsPerPage != nil {
		return *x.ItemsPerPage
	}
	return 0
}

type ListVacanciesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Vacancies     []*Vacancy             `protobuf:"bytes,1,rep,name=vacancies,proto3" json:"vacancies,omitempty"`
	PageInfo      *PageInfo              `protobuf:"bytes,2,opt,name=page_info,json=pageInfo,proto3" json:"page_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListVacanciesResponse) Reset() {
	*x = ListVacanciesResponse{}
	mi := &file_vacancy_v1_vacancy_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListVacanciesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListVacanciesResponse) ProtoMessage() {}

func (x *ListVacanciesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vacancy_v1_vacancy_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListVacanciesResponse.ProtoReflect.Descriptor instead.
func (*ListVacanciesResponse) Descriptor() ([]byte, []int) {
	return file_vacancy_v1_vacancy_proto_rawDescGZIP(), []int{3}
}

func (x *ListVacanciesResponse) GetVacancies() []*Vacancy {
	if x != nil {
		return x.Vacancies
	}
	return nil
}

func (x *ListVacanciesResponse) GetPageInfo() *PageInfo {
	if x != nil {
		return x.PageInfo
	}
	return nil
}

type PageInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	ItemsPerPage  int32                  `protobuf:"varint,2,opt,name=items_per_page,json=itemsPerPage,proto3" json:"items_per_page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PageInfo) Reset() {
	*x = PageInfo{}
	mi := &file_vacancy_v1_vacancy_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PageInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PageInfo) ProtoMessage() {}

func (x *PageInfo) ProtoReflect() protoreflect.Message {
	mi := &file_vacancy_v1_vacancy_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PageInfo.ProtoReflect.Descriptor instead.
func (*PageInfo) Descriptor() ([]byte, []int) {
	return file_vacancy_v1_vacancy_proto_rawDescGZIP(), []int{4}
}

func (x *PageInfo) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *PageInfo) GetItemsPerPage() int32 {
	if x != nil {
		return x.ItemsPerPage
	}
	return 0
}

type Company struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Company) Reset() {
	*x = Company{}
	mi := &file_vacancy_v1_vacancy_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Company) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Company) ProtoMessage() {}

func (x *Company) ProtoReflect() protoreflect.Message {
	mi := &file_vacancy_v1_vacancy_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Company.ProtoReflect.Descriptor instead.
func (*Company) Descriptor() ([]byte, []int) {
	return file_vacancy_v1_vacancy_proto_rawDescGZIP(), []int{5}
}

func (x *Company) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Company) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type Vacancy struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	CompanyId     int64                  `protobuf:"varint,4,opt,name=company_id,json=companyId,proto3" json:"company_id,omitempty"`
	Salary        float64                `protobuf:"fixed64,5,opt,name=salary,proto3" json:"salary,omitempty"`
	Link          string                 `protobuf:"bytes,6,opt,name=link,proto3" json:"link,omitempty"`
	City          string                 `protobuf:"bytes,7,opt,name=city,proto3" json:"city,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Company       *Company               `protobuf:"bytes,10,opt,name=company,proto3" json:"company,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Vacancy) Reset() {
	*x = Vacancy{}
	mi := &file_vacancy_v1_vacancy_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Vacancy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Vacancy) ProtoMessage() {}

func (x *Vacancy) ProtoReflect() protoreflect.Message {
	mi := &file_vacancy_v1_vacancy_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Vacancy.ProtoReflect.Descriptor instead.
func (*Vacancy) Descriptor() ([]byte, []int) {
	return file_vacancy_v1_vacancy_proto_rawDescGZIP(), []int{6}
}

func (x *Vacancy) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Vacancy) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Vacancy) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Vacancy) GetCompanyId() int64 {
	if x != nil {
		return x.CompanyId
	}
	return 0
}

func (x *Vacancy) GetSalary() float64 {
	if x != nil {
		return x.Salary
	}
	return 0
}

func (x *Vacancy) GetLink() string {
	if x != nil {
		return x.Link
	}
	return ""
}

func (x *Vacancy) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *Vacancy) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Vacancy) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Vacancy) GetCompany() *Company {
	if x != nil {
		return x.Company
	}
	return nil
}

var File_vacancy_v1_vacancy_proto protoreflect.FileDescriptor

const file_vacancy_v1_vacancy_proto_rawDesc = "" +
	"\n" +
	"\x18vacancy/v1/vacancy.proto\x12\x18jobaggregator.vacancy.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"#\n" +
	"\x11GetVacancyRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"Q\n" +
	"\x12GetVacancyResponse\x12;\n" +
	"\avacancy\x18\x01 \x01(\v2!.jobaggregator.vacancy.v1.VacancyR\avacancy\"v\n" +
	"\x14ListVacanciesRequest\x12\x17\n" +
	"\x04page\x18\x01 \x01(\x05H\x00R\x04page\x88\x01\x01\x12)\n" +
	"\x0eitems_per_page\x18\x02 \x01(\x05H\x01R\fitemsPerPage\x88\x01\x01B\a\n" +
	"\x05_pageB\x11\n" +
	"\x0f_items_per_page\"\x99\x01\n" +
	"\x15ListVacanciesResponse\x12?\n" +
	"\tvacancies\x18\x01 \x03(\v2!.jobaggregator.vacancy.v1.VacancyR\tvacancies\x12?\n" +
	"\tpage_info\x18\x02 \x01(\v2\".jobaggregator.vacancy.v1.PageInfoR\bpageInfo\"D\n" +
	"\bPageInfo\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12$\n" +
	"\x0eitems_per_page\x18\x02 \x01(\x05R\fitemsPerPage\"-\n" +
	"\aCompany\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"\xe3\x02\n" +
	"\aVacancy\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1d\n" +
	"\n" +
	"company_id\x18\x04 \x01(\x03R\tcompanyId\x12\x16\n" +
	"\x06salary\x18\x05 \x01(\x01R\x06salary\x12\x12\n" +
	"\x04link\x18\x06 \x01(\tR\x04link\x12\x12\n" +
	"\x04city\x18\a \x01(\tR\x04city\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12;\n" +
	"\acompany\x18\n" +
	" \x01(\v2!.jobaggregator.vacancy.v1.CompanyR\acompany2\xeb\x01\n" +
	"\x0eVacancyService\x12g\n" +
	"\n" +
	"GetVacancy\x12+.jobaggregator.vacancy.v1.GetVacancyRequest\x1a,.jobaggregator.vacancy.v1.GetVacancyResponse\x12p\n" +
	"\rListVacancies\x12..jobaggregator.vacancy.v1.ListVacanciesRequest\x1a/.jobaggregator.vacancy.v1.ListVacanciesResponseB5Z3vacancy_service/internal/proto/vacancy/v1;vacancyv1b\x06proto3"

var (
	file_vacancy_v1_vacancy_proto_rawDescOnce sync.Once
	file_vacancy_v1_vacancy_proto_rawDescData []byte
)

func file_vacancy_v1_vacancy_proto_rawDescGZIP() []byte {
	file_vacancy_v1_vacancy_proto_rawDescOnce.Do(func() {
		file_vacancy_v1_vacancy_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_vacancy_v1_vacancy_proto_rawDesc), len(file_vacancy_v1_vacancy_proto_rawDesc)))
	})
	return file_vacancy_v1_vacancy_proto_rawDescData
}

var file_vacancy_v1_vacancy_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_vacancy_v1_vacancy_proto_goTypes = []any{
	(*GetVacancyRequest)(nil),     // 0: jobaggregator.vacancy.v1.GetVacancyRequest
	(*GetVacancyResponse)(nil),    // 1: jobaggregator.vacancy.v1.GetVacancyResponse
	(*ListVacanciesRequest)(nil),  // 2: jobaggregator.vacancy.v1.ListVacanciesRequest
	(*ListVacanciesResponse)(nil), // 3: jobaggregator.vacancy.v1.ListVacanciesResponse
	(*PageInfo)(nil),              // 4: jobaggregator.vacancy.v1.PageInfo
	(*Company)(nil),               // 5: jobaggregator.vacancy.v1.Company
	(*Vacancy)(nil),               // 6: jobaggregator.vacancy.v1.Vacancy
	(*timestamppb.Timestamp)(nil), // 7: google.protobuf.Timestamp
}
var file_vacancy_v1_vacancy_proto_depIdxs = []int32{
	6, // 0: jobaggregator.vacancy.v1.GetVacancyResponse.vacancy:type_name -> jobaggregator.vacancy.v1.Vacancy
	6, // 1: jobaggregator.vacancy.v1.ListVacanciesResponse.vacancies:type_name -> jobaggregator.vacancy.v1.Vacancy
	4, // 2: jobaggregator.vacancy.v1.ListVacanciesResponse.page_info:type_name -> jobaggregator.vacancy.v1.PageInfo
	7, // 3: jobaggregator.vacancy.v1.Vacancy.created_at:type_name -> google.protobuf.Timestamp
	7, // 4: jobaggregator.vacancy.v1.Vacancy.updated_at:type_name -> google.protobuf.Timestamp
	5, // 5: jobaggregator.vacancy.v1.Vacancy.company:type_name -> jobaggregator.vacancy.v1.Company
	0, // 6: jobaggregator.vacancy.v1.VacancyService.GetVacancy:input_type -> jobaggregator.vacancy.v1.GetVacancyRequest
	2, // 7: jobaggregator.vacancy.v1.VacancyService.ListVacancies:input_type -> jobaggregator.vacancy.v1.ListVacanciesRequest
	1, // 8: jobaggregator.vacancy.v1.VacancyService.GetVacancy:output_type -> jobaggregator.vacancy.v1.GetVacancyResponse
	3, // 9: jobaggregator.vacancy.v1.VacancyService.ListVacancies:output_type -> jobaggregator.vacancy.v1.ListVacanciesResponse
	8, // [8:10] is the sub-list for method output_type
	6, // [6:8] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_vacancy_v1_vacancy_proto_init() }
func file_vacancy_v1_vacancy_proto_init() {
	if File_vacancy_v1_vacancy_proto != nil {
		return
	}
	file_vacancy_v1_vacancy_proto_msgTypes[2].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_vacancy_v1_vacancy_proto_rawDesc), len(file_vacancy_v1_vacancy_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_vacancy_v1_vacancy_proto_goTypes,
		DependencyIndexes: file_vacancy_v1_vacancy_proto_depIdxs,
		MessageInfos:      file_vacancy_v1_vacancy_proto_msgTypes,
	}.Build()
	File_vacancy_v1_vacancy_proto = out.File
	file_vacancy_v1_vacancy_proto_goTypes = nil
	file_vacancy_v1_vacancy_proto_depIdxs = nil
}
