// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: vacancy/v1/vacancy.proto

package vacancyv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	VacancyService_GetVacancy_FullMethodName           = "/jobaggregator.vacancy.v1.VacancyService/GetVacancy"
	VacancyService_ListVacancies_FullMethodName        = "/jobaggregator.vacancy.v1.VacancyService/ListVacancies"
	VacancyService_CreateVacancy_FullMethodName        = "/jobaggregator.vacancy.v1.VacancyService/CreateVacancy"
	VacancyService_BatchCreateVacancies_FullMethodName = "/jobaggregator.vacancy.v1.VacancyService/BatchCreateVacancies"
)

// VacancyServiceClient is the client API for VacancyService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type VacancyServiceClient interface {
	GetVacancy(ctx context.Context, in *GetVacancyRequest, opts ...grpc.CallOption) (*GetVacancyResponse, error)
	ListVacancies(ctx context.Context, in *ListVacanciesRequest, opts ...grpc.CallOption) (*ListVacanciesResponse, error)
	CreateVacancy(ctx context.Context, in *CreateVacancyRequest, opts ...grpc.CallOption) (*CreateVacancyResponse, error)
	BatchCreateVacancies(ctx context.Context, in *BatchCreateVacanciesRequest, opts ...grpc.CallOption) (*BatchCreateVacanciesResponse, error)
}

type vacancyServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewVacancyServiceClient(cc grpc.ClientConnInterface) VacancyServiceClient {
	return &vacancyServiceClient{cc}
}

func (c *vacancyServiceClient) GetVacancy(ctx context.Context, in *GetVacancyRequest, opts ...grpc.CallOption) (*GetVacancyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetVacancyResponse)
	err := c.cc.Invoke(ctx, VacancyService_GetVacancy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vacancyServiceClient) ListVacancies(ctx context.Context, in *ListVacanciesRequest, opts ...grpc.CallOption) (*ListVacanciesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListVacanciesResponse)
	err := c.cc.Invoke(ctx, VacancyService_ListVacancies_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vacancyServiceClient) CreateVacancy(ctx context.Context, in *CreateVacancyRequest, opts ...grpc.CallOption) (*CreateVacancyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateVacancyResponse)
	err := c.cc.Invoke(ctx, VacancyService_CreateVacancy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vacancyServiceClient) BatchCreateVacancies(ctx context.Context, in *BatchCreateVacanciesRequest, opts ...grpc.CallOption) (*BatchCreateVacanciesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BatchCreateVacanciesResponse)
	err := c.cc.Invoke(ctx, VacancyService_BatchCreateVacancies_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VacancyServiceServer is the server API for VacancyService service.
// All implementations must embed UnimplementedVacancyServiceServer
// for forward compatibility.
type VacancyServiceServer interface {
	GetVacancy(context.Context, *GetVacancyRequest) (*GetVacancyResponse, error)
	ListVacancies(context.Context, *ListVacanciesRequest) (*ListVacanciesResponse, error)
	CreateVacancy(context.Context, *CreateVacancyRequest) (*CreateVacancyResponse, error)
	BatchCreateVacancies(context.Context, *BatchCreateVacanciesRequest) (*BatchCreateVacanciesResponse, error)
	mustEmbedUnimplementedVacancyServiceServer()
}

// UnimplementedVacancyServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedVacancyServiceServer struct{}

func (UnimplementedVacancyServiceServer) GetVacancy(context.Context, *GetVacancyRequest) (*GetVacancyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetVacancy not implemented")
}
func (UnimplementedVacancyServiceServer) ListVacancies(context.Context, *ListVacanciesRequest) (*ListVacanciesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListVacancies not implemented")
}
func (UnimplementedVacancyServiceServer) CreateVacancy(context.Context, *CreateVacancyRequest) (*CreateVacancyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateVacancy not implemented")
}
func (UnimplementedVacancyServiceServer) BatchCreateVacancies(context.Context, *BatchCreateVacanciesRequest) (*BatchCreateVacanciesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method BatchCreateVacancies not implemented")
}
func (UnimplementedVacancyServiceServer) mustEmbedUnimplementedVacancyServiceServer() {}
func (UnimplementedVacancyServiceServer) testEmbeddedByValue()                        {}

// UnsafeVacancyServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to VacancyServiceServer will
// result in compilation errors.
type UnsafeVacancyServiceServer interface {
	mustEmbedUnimplementedVacancyServiceServer()
}

func RegisterVacancyServiceServer(s grpc.ServiceRegistrar, srv VacancyServiceServer) {
	// If the following call panics, it indicates UnimplementedVacancyServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&VacancyService_ServiceDesc, srv)
}

func _VacancyService_GetVacancy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetVacancyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VacancyServiceServer).GetVacancy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VacancyService_GetVacancy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VacancyServiceServer).GetVacancy(ctx, req.(*GetVacancyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VacancyService_ListVacancies_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListVacanciesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VacancyServiceServer).ListVacancies(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VacancyService_ListVacancies_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VacancyServiceServer).ListVacancies(ctx, req.(*ListVacanciesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VacancyService_CreateVacancy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateVacancyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VacancyServiceServer).CreateVacancy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VacancyService_CreateVacancy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VacancyServiceServer).CreateVacancy(ctx, req.(*CreateVacancyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VacancyService_BatchCreateVacancies_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchCreateVacanciesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VacancyServiceServer).BatchCreateVacancies(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VacancyService_BatchCreateVacancies_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VacancyServiceServer).BatchCreateVacancies(ctx, req.(*BatchCreateVacanciesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// VacancyService_ServiceDesc is the grpc.ServiceDesc for VacancyService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var VacancyService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "jobaggregator.vacancy.v1.VacancyService",
	HandlerType: (*VacancyServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetVacancy",
			Handler:    _VacancyService_GetVacancy_Handler,
		},
		{
			MethodName: "ListVacancies",
			Handler:    _VacancyService_ListVacancies_Handler,
		},
		{
			MethodName: "CreateVacancy",
			Handler:    _VacancyService_CreateVacancy_Handler,
		},
		{
			MethodName: "BatchCreateVacancies",
			Handler:    _VacancyService_BatchCreateVacancies_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "vacancy/v1/vacancy.proto",
}
