FROM golang:1.25-alpine

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN CGO_ENABLED=0 go build -o /usr/local/bin/vacancy-healthcheck ./cmd/healthcheck

EXPOSE 50051

CMD ["go", "run", "./cmd/api"]
