// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Company struct {
	ID   int32  `json:"id"`
	Name string `json:"name"`
}

type Vacancy struct {
	ID          int32            `json:"id"`
	Title       string           `json:"title"`
	Description string           `json:"description"`
	CompanyId   int32            `json:"companyId"`
	Salary      float64          `json:"salary"`
	Link        string           `json:"link"`
	City        string           `json:"city"`
	CreatedAt   pgtype.Timestamp `json:"createdAt"`
	UpdatedAt   pgtype.Timestamp `json:"updatedAt"`
}
