// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"
)

type Querier interface {
	GetVacancyByID(ctx context.Context, id int32) (GetVacancyByIDRow, error)
	// sqlc reads this file and generates Go methods from each annotated query.
	// Example: "-- name: ListVacancies :many" becomes queries.ListVacancies(ctx, params).
	ListVacancies(ctx context.Context, arg ListVacanciesParams) ([]ListVacanciesRow, error)
	ListVacanciesByCompany(ctx context.Context, name string) ([]ListVacanciesByCompanyRow, error)
	ListVacanciesBySalaryRange(ctx context.Context, arg ListVacanciesBySalaryRangeParams) ([]ListVacanciesBySalaryRangeRow, error)
	UpsertCompany(ctx context.Context, name string) (int32, error)
	// Upsert means: insert if link is new, update if link already exists.
	// This is important for parser imports where the same vacancy can be seen repeatedly.
	UpsertVacancy(ctx context.Context, arg UpsertVacancyParams) (UpsertVacancyRow, error)
}

var _ Querier = (*Queries)(nil)
