// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: vacancy.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getVacancyByID = `-- name: GetVacancyByID :one
SELECT 
    vacancy.id, vacancy.title, vacancy.description, vacancy."companyId", vacancy.salary, vacancy.link, vacancy.city, vacancy."createdAt", vacancy."updatedAt",
    company.id, company.name
FROM "Vacancy" vacancy
JOIN "Company" company ON company."id" = vacancy."companyId"
WHERE vacancy."id" = $1
`

type GetVacancyByIDRow struct {
	Vacancy Vacancy `json:"vacancy"`
	Company Company `json:"company"`
}

func (q *Queries) GetVacancyByID(ctx context.Context, id int32) (GetVacancyByIDRow, error) {
	row := q.db.QueryRow(ctx, getVacancyByID, id)
	var i GetVacancyByIDRow
	err := row.Scan(
		&i.Vacancy.ID,
		&i.Vacancy.Title,
		&i.Vacancy.Description,
		&i.Vacancy.CompanyId,
		&i.Vacancy.Salary,
		&i.Vacancy.Link,
		&i.Vacancy.City,
		&i.Vacancy.CreatedAt,
		&i.Vacancy.UpdatedAt,
		&i.Company.ID,
		&i.Company.Name,
	)
	return i, err
}

const listVacancies = `-- name: ListVacancies :many

SELECT 
    vacancy.id, vacancy.title, vacancy.description, vacancy."companyId", vacancy.salary, vacancy.link, vacancy.city, vacancy."createdAt", vacancy."updatedAt",
    company.id, company.name
FROM "Vacancy" vacancy
JOIN "Company" company ON company."id" = vacancy."companyId"
ORDER BY vacancy."createdAt" DESC, vacancy."id" DESC
LIMIT $1 OFFSET $2
`

type ListVacanciesParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListVacanciesRow struct {
	Vacancy Vacancy `json:"vacancy"`
	Company Company `json:"company"`
}

// sqlc reads this file and generates Go methods from each annotated query.
// Example: "-- name: ListVacancies :many" becomes queries.ListVacancies(ctx, params).
func (q *Queries) ListVacancies(ctx context.Context, arg ListVacanciesParams) ([]ListVacanciesRow, error) {
	rows, err := q.db.Query(ctx, listVacancies, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListVacanciesRow{}
	for rows.Next() {
		var i ListVacanciesRow
		if err := rows.Scan(
			&i.Vacancy.ID,
			&i.Vacancy.Title,
			&i.Vacancy.Description,
			&i.Vacancy.CompanyId,
			&i.Vacancy.Salary,
			&i.Vacancy.Link,
			&i.Vacancy.City,
			&i.Vacancy.CreatedAt,
			&i.Vacancy.UpdatedAt,
			&i.Company.ID,
			&i.Company.Name,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVacanciesByCompany = `-- name: ListVacanciesByCompany :many
SELECT
    vacancy.id, vacancy.title, vacancy.description, vacancy."companyId", vacancy.salary, vacancy.link, vacancy.city, vacancy."createdAt", vacancy."updatedAt",
    company.id, company.name
FROM "Vacancy" vacancy
JOIN "Company" company ON company."id" = vacancy."companyId"
WHERE company."name" = $1
ORDER BY vacancy."createdAt" DESC, vacancy."id" DESC
`

type ListVacanciesByCompanyRow struct {
	Vacancy Vacancy `json:"vacancy"`
	Company Company `json:"company"`
}

func (q *Queries) ListVacanciesByCompany(ctx context.Context, name string) ([]ListVacanciesByCompanyRow, error) {
	rows, err := q.db.Query(ctx, listVacanciesByCompany, name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListVacanciesByCompanyRow{}
	for rows.Next() {
		var i ListVacanciesByCompanyRow
		if err := rows.Scan(
			&i.Vacancy.ID,
			&i.Vacancy.Title,
			&i.Vacancy.Description,
			&i.Vacancy.CompanyId,
			&i.Vacancy.Salary,
			&i.Vacancy.Link,
			&i.Vacancy.City,
			&i.Vacancy.CreatedAt,
			&i.Vacancy.UpdatedAt,
			&i.Company.ID,
			&i.Company.Name,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVacanciesBySalaryRange = `-- name: ListVacanciesBySalaryRange :many
SELECT
    vacancy.id, vacancy.title, vacancy.description, vacancy."companyId", vacancy.salary, vacancy.link, vacancy.city, vacancy."createdAt", vacancy."updatedAt",
    company.id, company.name
FROM "Vacancy" vacancy
JOIN "Company" company ON company."id" = vacancy."companyId"
WHERE vacancy."salary" >= $1 AND vacancy."salary" <= $2
ORDER BY vacancy."salary" DESC, vacancy."createdAt" DESC
`

type ListVacanciesBySalaryRangeParams struct {
	Salary   float64 `json:"salary"`
	Salary_2 float64 `json:"salary_2"`
}

type ListVacanciesBySalaryRangeRow struct {
	Vacancy Vacancy `json:"vacancy"`
	Company Company `json:"company"`
}

func (q *Queries) ListVacanciesBySalaryRange(ctx context.Context, arg ListVacanciesBySalaryRangeParams) ([]ListVacanciesBySalaryRangeRow, error) {
	rows, err := q.db.Query(ctx, listVacanciesBySalaryRange, arg.Salary, arg.Salary_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListVacanciesBySalaryRangeRow{}
	for rows.Next() {
		var i ListVacanciesBySalaryRangeRow
		if err := rows.Scan(
			&i.Vacancy.ID,
			&i.Vacancy.Title,
			&i.Vacancy.Description,
			&i.Vacancy.CompanyId,
			&i.Vacancy.Salary,
			&i.Vacancy.Link,
			&i.Vacancy.City,
			&i.Vacancy.CreatedAt,
			&i.Vacancy.UpdatedAt,
			&i.Company.ID,
			&i.Company.Name,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertCompany = `-- name: UpsertCompany :one
INSERT INTO "Company" ("name")
VALUES ($1)
ON CONFLICT ("name") DO UPDATE SET "name" = EXCLUDED."name"
RETURNING "id"
`

func (q *Queries) UpsertCompany(ctx context.Context, name string) (int32, error) {
	row := q.db.QueryRow(ctx, upsertCompany, name)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const upsertVacancy = `-- name: UpsertVacancy :one
INSERT INTO "Vacancy" ("title", "description", "companyId", "salary", "link", "city", "updatedAt")
VALUES ($1, $2, $3, $4, $5, $6, CURRENT_TIMESTAMP)
ON CONFLICT ("link") DO UPDATE SET
    "title" = EXCLUDED."title",
    "description" = EXCLUDED."description",
    "companyId" = EXCLUDED."companyId",
    "salary" = EXCLUDED."salary",
    "city" = EXCLUDED."city",
    "updatedAt" = CURRENT_TIMESTAMP
RETURNING
    "id" AS id,
    "title" AS title,
    "description" AS description,
    "companyId" AS company_id,
    "salary" AS salary,
    "link" AS link,
    "city" AS city,
    "createdAt" AS created_at,
    "updatedAt" AS updated_at
`

type UpsertVacancyParams struct {
	Title       string  `json:"title"`
	Description string  `json:"description"`
	CompanyId   int32   `json:"companyId"`
	Salary      float64 `json:"salary"`
	Link        string  `json:"link"`
	City        string  `json:"city"`
}

type UpsertVacancyRow struct {
	ID          int32            `json:"id"`
	Title       string           `json:"title"`
	Description string           `json:"description"`
	CompanyID   int32            `json:"company_id"`
	Salary      float64          `json:"salary"`
	Link        string           `json:"link"`
	City        string           `json:"city"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	UpdatedAt   pgtype.Timestamp `json:"updated_at"`
}

// Upsert means: insert if link is new, update if link already exists.
// This is important for parser imports where the same vacancy can be seen repeatedly.
func (q *Queries) UpsertVacancy(ctx context.Context, arg UpsertVacancyParams) (UpsertVacancyRow, error) {
	row := q.db.QueryRow(ctx, upsertVacancy,
		arg.Title,
		arg.Description,
		arg.CompanyId,
		arg.Salary,
		arg.Link,
		arg.City,
	)
	var i UpsertVacancyRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.CompanyID,
		&i.Salary,
		&i.Link,
		&i.City,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
